### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by nightrid3r** [tsiv/ccminer-cryptonight#3]
autogen.sh complains about libs being in a subdir and doesn't genereate configure file.
configure.sh doesn't work for lack of configure file.
now makefile is generated so i can't compile

On ubuntu 14.04

**Comment by tsiv** [comment]
Include the output of autogen.sh, sounds pretty strange.

**Comment by nightrid3r** [comment]
Op 23-07-14 om 07:31 schreef tsiv:

**Comment by tsiv** [comment]
Does adding the following line to the start of Makefile.am fix the problem?

AUTOMAKE_OPTIONS = subdir-objects

**Comment by nightrid3r** [comment]
i restarted from scratch, now it works.
looks like a git clone problem of some sorts.
the autome option indeed solves the warnings.

Michel

Op 23-07-14 om 12:11 schreef tsiv:

**Comment by tsiv** [comment]
Apparently automake exits with an error code on warnings and since autogen.sh is just "aclocal && autoheader && automake --add-missing --gnu --copy && autoconf" autoconf doesn't get run, leaving the build without configure. Pushed the Makefile.am addition, should also future-proof for the upcoming automake 2.0 update. I believe that's solved, thanks for the report.
