### ISSUE TITLE
"result for nonce $numberhere does not validate on CPU!"

### ISSUE THREAD

**Issue by babybonobo** [tsiv/ccminer-cryptonight#7]
I am trying to use a GTX 970 to mine cryptonight (XDN).  I used to have a GTX 570 that worked great.  Now that I've upgraded all I get is the error "result for nonce $numberhere does not validate on CPU!"

Any idea?

**Comment by babybonobo** [comment]
Latest driver does not work, had to downgrade my Nvidia driver and it works now.

**Comment by SentinalBais** [comment]
I am getting this error on my 980ti is this a warning? I am not allays getting the error though

**Comment by deshi-basara** [comment]
Try the ccminer-cryptonight fork of KlausT: [https://github.com/KlausT/ccminer-cryptonight](https://github.com/KlausT/ccminer-cryptonight).

He [fixed](https://github.com/KlausT/ccminer-cryptonight/commit/94497800c74fdffbe46db8a7bab53832c456284e) the nonce-calculation some days ago. Since switching to his fork I never had a nonce-error on my GTX 1060 again, give it a try.

**Comment by creolis** [comment]
I noticed that ccminer-cryptonight by KlausT is not compiling due to an error (at least on my setup)

`undefined reference to cuda_devicereset`

So I just used the cpu-miner.c from KlausT (direct link [here](https://raw.githubusercontent.com/KlausT/ccminer-cryptonight/94497800c74fdffbe46db8a7bab53832c456284e/cpu-miner.c)) instead of cpu-miner.c in this repository and it recompiled.

Works perfectly (for me :-) and gets rid of the nonce validation troubles.
